import sys,os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from langgraph.graph import StateGraph, START, END
from SarvamModel import SarvamModel
from NormalModel import NormalModel
from models.Prompt import Prompt
from typing import TypedDict, Annotated
from langchain_core.messages import BaseMessage
from sarvamai import SarvamAI
# from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph.message import add_messages
from dotenv import load_dotenv
from langchain_core.messages import AIMessage
from pydantic import BaseModel, Field
from langchain_core.output_parsers import PydanticOutputParser
from fastapi import FastAPI
app = FastAPI()
class AnswerEntities(BaseModel):
    user_input: str=Field(
        description="user input to the model",
    )
    answer: str = Field(
        description="Answer generated by the model",
    )
parser=PydanticOutputParser(pydantic_object=AnswerEntities)
load_dotenv()
class JokeState(TypedDict):

    topic: str
    joke: str
    explanation: str
    messages: Annotated[list[BaseMessage], add_messages]


class ChatState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]





def generate_joke(state: JokeState):
    user_input=state["topic"]
    prompt_text= f"generate a joke on the topic {user_input}"
    prompt=Prompt(prompt_text,parser=None,input_variables=["user_input"])
    model=NormalModel(api_key="sk_e9hrwjet_SJrtYF4VYTYd474dsVN5Krd4",prompt=prompt)
    response=model.invoke()

    return {'joke': response}
def generate_explanation(state: JokeState):

    user_input=state["joke"]
    prompt_text= f"generate a joke on the topic {user_input}"
    prompt=Prompt(prompt_text,parser=None,input_variables=["user_input"])
    model=NormalModel(api_key="sk_e9hrwjet_SJrtYF4VYTYd474dsVN5Krd4",prompt=prompt)
    response=model.invoke()
    
    return {'explanation': response}

def combine_content(state: JokeState):
    content="topic :"+" "+state['topic']+" ,"+"joke :"+" "+state["joke"] + " ," + "explanation :"+" "+state["explanation"]
    return {'messages': [AIMessage(content=content)]}
print("Prompt template created successfully.")



# graph = StateGraph(JokeState)

# graph.add_node('generate_joke', generate_joke)
# graph.add_node('generate_explanation', generate_explanation)
# graph.add_node('combine_content', combine_content)

# graph.add_edge(START, 'generate_joke')
# graph.add_edge('generate_joke', 'generate_explanation')
# graph.add_edge('generate_explanation', 'combine_content')
# graph.add_edge('combine_content', END)
def chat_node(state: ChatState):
    user_input = state['messages']


    prompt_text= f"generate a joke on the topic {user_input}"
    prompt=Prompt(prompt_text,parser=None,input_variables=["user_input"])
    model=NormalModel(api_key="sk_e9hrwjet_SJrtYF4VYTYd474dsVN5Krd4",prompt=prompt)
    response=model.invoke()
    return {"messages": [response]}

# Checkpointer
checkpointer = InMemorySaver()

graph = StateGraph(ChatState)
graph.add_node("chat_node", chat_node)
graph.add_edge(START, "chat_node")
graph.add_edge("chat_node", END)
checkpointer = InMemorySaver()





workflow = graph.compile(checkpointer=checkpointer)
class LastConversation(BaseModel):
      id: str = Field(..., example="1")

class TopicHistory(BaseModel):

      id: str = Field(..., example="1")
class TopicInput(BaseModel):
    topic: str = Field(..., example="pizza")
    id: str = Field(..., example="1")

@app.post("/invoke")
def invoke_workflow(data: TopicInput):
    config1 = {"configurable": {"thread_id": data.id}}

    response=workflow.invoke({'topic':data.topic}, config=config1)
    return response
@app.post("/history")
def invoke_workflow(data: TopicHistory):
    config = {"configurable": {"thread_id": data.id}}

    response=list(workflow.get_state_history(config))
    return response
@app.post("/load_conversation")
def invoke_workflow(data: LastConversation):
    config = {"configurable": {"thread_id": data.id}}

    state=list(workflow.get_state(config=config))
    return state[0].get('messages',[])

# config1 = {"configurable": {"thread_id": "1"}}

# response=workflow.invoke({'topic':'pizza'}, config=config1)
# response=workflow.get_state(config1)
# response=list(workflow.get_state_history(config1))
# workflow.stream()
# for message_chunk, metadata in workflow.stream( input= {'topic':'ice cream'},
#                 config= config1,
#                 stream_mode= 'messages'):
#         for chunk in message_chunk.content:
#              print(chunk,end=' ')
# print(response)

# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port=8000)
