import sys,os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from langgraph.graph import StateGraph, START, END
from SarvamModel import SarvamModel
from NormalModel import NormalModel
from models.Prompt import Prompt
from typing import TypedDict, Annotated
from langchain_core.messages import BaseMessage
from sarvamai import SarvamAI
# from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.checkpoint.sqlite import SqliteSaver
import sqlite3
from langgraph.graph.message import add_messages
from dotenv import load_dotenv
from langchain_core.messages import AIMessage,HumanMessage
from typing import Literal,Union
from pydantic import BaseModel, Field
from langchain_core.output_parsers import PydanticOutputParser
from fastapi import FastAPI
app = FastAPI()
class AnswerEntities(BaseModel):
    user_input: str=Field(
        description="user input to the model",
    )
    answer: str = Field(
        description="Answer generated by the model",
    )
parser=PydanticOutputParser(pydantic_object=AnswerEntities)
load_dotenv()
class JokeState(TypedDict):

    topic: str
    joke: str
    explanation: str
    messages: Annotated[list[BaseMessage], add_messages]
class RandomNumberInput(BaseModel):
    pass

class BringTodoItemInput(BaseModel):
    id: int

class SpecialAddInput(BaseModel):
    a: int
    b: int

class ToolCall(BaseModel):
     content: str = Field(default="", description="Content from the model")
     tool_called:Literal["True", "False"]=Field( description="Whether a provided tool used or not")
     tool_name: Literal["random_number","bring_todo_item","special_add"]=Field( description="Name of the tool called")

     input_schema: Union[RandomNumberInput, BringTodoItemInput, SpecialAddInput]=Field(default={}, description="Input schema for the tool in format {'parameter_name1': 'value','parameter_name2': 'value'} only")


parser=PydanticOutputParser(pydantic_object=ToolCall)
class ChatState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    user_id: str=Field(..., example="523")
    tool_called:Literal["True", "False"]=Field( description="Whether a provided tool used or not")
    tools_list:list=Field(default=[], description="List of tools available")
    tool_name: Literal["random_number","bring_todo_item","special_add"]=Field( description="Name of the tool called")

    input_schema:Union[RandomNumberInput, BringTodoItemInput, SpecialAddInput]=Field(default={}, description="Input schema for the tool in format {'parameter_name1': 'value','parameter_name2': 'value'} only")







# def generate_joke(state: JokeState):
#     user_input=state["topic"]
#     prompt_text= f"generate a joke on the topic {user_input}"
#     prompt=Prompt(prompt_text,parser=None,input_variables=["user_input"])
#     model=NormalModel(api_key="sk_e9hrwjet_SJrtYF4VYTYd474dsVN5Krd4",prompt=prompt)
#     response=model.invoke()

#     return {'joke': response}
# def generate_explanation(state: JokeState):

#     user_input=state["joke"]
#     prompt_text= f"generate a joke on the topic {user_input}"
#     prompt=Prompt(prompt_text,parser=None,input_variables=["user_input"])
#     model=NormalModel(api_key="sk_e9hrwjet_SJrtYF4VYTYd474dsVN5Krd4",prompt=prompt)
#     response=model.invoke()
    
#     return {'explanation': response}

# def combine_content(state: JokeState):
#     content="topic :"+" "+state['topic']+" ,"+"joke :"+" "+state["joke"] + " ," + "explanation :"+" "+state["explanation"]
#     return {'messages': [AIMessage(content=content)]}
# print("Prompt template created successfully.")



# graph = StateGraph(JokeState)

# graph.add_node('generate_joke', generate_joke)
# graph.add_node('generate_explanation', generate_explanation)
# graph.add_node('combine_content', combine_content)

# graph.add_edge(START, 'generate_joke')
# graph.add_edge('generate_joke', 'generate_explanation')
# graph.add_edge('generate_explanation', 'combine_content')
# graph.add_edge('combine_content', END)
import json
def chat_node(state: ChatState):
    user_input = state['messages']
    tools_list=state['tools_list']

    # print("Available tools:", tools_list)
    # print(user_input)
    tool_info = [f"ID of tool:{idx} - tool name: {t.name} — tool description: {t.description} — input_schema: {t.inputSchema['properties']}" for idx,t in enumerate(tools_list)]
    tools = "\n".join(tool_info)
    print("Available tools:", tools)
    # print(user_input)

    prompt_text= f"""
You are given these tools:
{{tools}}

Each tool has a specific input schema. 
When you output your result, make sure your "input_schema" strictly follows the tool's defined schema. 
Do not create new keys or arrays.
RULE:
if use same variable name that mentions in input schema of tool.
if the user query is not related to any tool then do not call any tool and give answer



Now answer the following user query using the provided tools if necessary:
{user_input[-1].content}
"""

    # prompt_text= f"Give name of tool that can be possibly use for given user query  tools:{{tools}} user query : {user_input[-1].content}"

    prompt=Prompt(prompt_text,parser=parser,input_variables=["tools","user_input"])
    model=NormalModel(api_key="sk_e9hrwjet_SJrtYF4VYTYd474dsVN5Krd4",prompt=prompt)
    response=model.invoke()
    print("Raw response from model:", response)
    response=response.replace('```json','')
    response=response.replace('```','')

    response=json.loads(response)

    # print("Response from model:", response)
    # return {"messages": [user_input[0], AIMessage(content=response)]}
    if response['content']!='':
       return {"messages": [user_input[0], AIMessage(content=response['content'])],"tool_name": response['tool_name'],"input_schema":response['input_schema'],"tool_called":response['tool_called']}
    else:
        return {"messages": [user_input[0]],"tool_name": response['tool_name'],"input_schema":response['input_schema'],"tool_called":response['tool_called']}

# Checkpointer
# checkpointer = InMemorySaver()
from fastmcp import Client
import asyncio
async def main():
    # Connect via stdio to a local script
    # if state['tools_list']:
    #     return {'tools_list': state['tools_list']}
        

    async with Client("server.py") as client:
        tools = await client.list_tools()
        # print(f"Available tools: {tools}")
    return tools

def tool_list(state: ChatState):
    tools=asyncio.run(main())
    return {'tools_list': tools}

def tool_condition(state: ChatState):
    print("Tool condition check:", state.get('tool_called', 'False'))
    if state.get('tool_called', 'False')=='True':
        return 'tool_call'
    else:
        return END
async def tool_call_main(state: ChatState):
          async with Client("server.py") as client:
               result = await client.call_tool(state['tool_name'], state['input_schema'])
          return result
def tool_call(state: ChatState):
    result=asyncio.run(tool_call_main(state))
    print("Tool call result:", AIMessage(content=result.content[0].text))
    return {'messages': [AIMessage(content=result.content[0].text)]}
        # result = await client.call_tool("random_number", {})
        # print(f"Result: {result.content[0].text}")
graph = StateGraph(ChatState)
graph.add_node('list_tools', tool_list)

graph.add_node("chat_node", chat_node)
graph.add_node("tool_call", tool_call)


graph.add_edge(START, 'list_tools')

graph.add_edge('list_tools', 'chat_node')

graph.add_conditional_edges('chat_node', tool_condition)
graph.add_edge('tool_call', END)
# graph.add_edge(START, "chat_node")
graph.add_edge("chat_node", END)
# checkpointer = InMemorySaver()
conn = sqlite3.connect(database='chatbot.db', check_same_thread=False)
# Checkpointer
checkpointer = SqliteSaver(conn=conn)
# print(type(checkpointer))
# user_id="523"


workflow = graph.compile(checkpointer=checkpointer)
print(workflow)
class LastConversation(BaseModel):
      id: str = Field(..., example="1")

class TopicHistory(BaseModel):

      id: str = Field(..., example="1")
class TopicInput(BaseModel):
    user_input: str = Field(..., example="what is capital of Delhi?")
    id: str = Field(..., example="1")
def retrieve_all_threads():
    all_threads = set()
    for checkpoint in checkpointer.list(None):
        all_threads.add(checkpoint.config['configurable']['thread_id'])

    return list(all_threads)
@app.post("/invoke/{user_id}")
def invoke_workflow(data: TopicInput,user_id: str):
    config = {"configurable": {"thread_id": user_id+"@"+data.id}}

    response=workflow.invoke({'messages':data.user_input,'user_id':user_id}, config=config)
    item = response.get('messages', [])
    # print("Final response:", item)
    response['messages'] = item[::-1]  # Reverse the messages list to have the latest message first
    return response
@app.post("/history/{user_id}")
def invoke_workflow(data: TopicHistory,user_id: str):
    config = {"configurable": {"thread_id":  user_id+"@"+data.id}}

    response=list(workflow.get_state_history(config))
    return response
@app.post("/load_conversation/{user_id}")
def invoke_workflow(data: LastConversation,user_id: str):
    config = {"configurable": {"thread_id": user_id+"@"+data.id}}

    state=list(workflow.get_state(config=config))
    return state[0].get('messages',[])
@app.get("/all_threads")
def invoke_workflow():
    threads = retrieve_all_threads()
    return threads


# config1 = {"configurable": {"thread_id": "1"}}

# response=workflow.invoke({'topic':'pizza'}, config=config1)
# response=workflow.get_state(config1)
# response=list(workflow.get_state_history(config1))
# workflow.stream()
# for message_chunk, metadata in workflow.stream( input= {'topic':'ice cream'},
#                 config= config1,
#                 stream_mode= 'messages'):
#         for chunk in message_chunk.content:
#              print(chunk,end=' ')
# print(response)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
