# from dataclasses import Field

import sys,os

from pydantic import BaseModel
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from langgraph.graph import StateGraph, START, END
from typing import TypedDict, Annotated
from langchain_core.messages import BaseMessage, HumanMessage
# from langchain_openai import ChatOpenAI
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.prebuilt import ToolNode, tools_condition,create_react_agent
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_core.tools import tool
from langchain.tools import StructuredTool
# from langchain.chat_models import ChatOpenAI
import requests
import random

from NormalModel import NormalModel
from models.Prompt import Prompt

class AnswerEntities(BaseModel):
    user_input: str=Field(
        description="user input to the model",
    )
    answer: str = Field(
        description="Answer generated by the model",
    )
parser=PydanticOutputParser(pydantic_object=AnswerEntities)
# Tools
# search_tool = DuckDuckGoSearchRun(region="us-en")

import json
@tool
def calculator(user_input: str) -> dict:
    """
    Perform basic arithmetic operations.
    Input format (JSON): {"first_num": 5, "second_num": 3, "operation": "mul"}
    """
    try:
        data = json.loads(user_input)
        a = data["first_num"]
        b = data["second_num"]
        op = data["operation"]

        if op == "add":
            result = a + b
        elif op == "sub":
            result = a - b
        elif op == "mul":
            result = a * b
        elif op == "div":
            if b == 0:
                return {"error": "Division by zero"}
            result = a / b
        else:
            return {"error": f"Unsupported operation '{op}'"}

        return {"result": result}
    except Exception as e:
        return {"error": str(e)}
    
@tool
def fetch_title(url)->str:
    """
    Fetch the title of a webpage given its URL.
    """
    try:
        response = requests.get(url)
        print(response)
        if response.status_code == 200:
            title=response
            return title
        else:
            return f"Failed to retrieve webpage. Status code: {response.status_code}"
    except Exception as e:
        return str(e)
@tool
def get_stock_price(symbol: str) -> dict:
    """
    Fetch latest stock price for a given symbol (e.g. 'AAPL', 'TSLA') 
    using Alpha Vantage with API key in the URL.
    """
    url = f"https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={symbol}&apikey=C9PE94QUEW9VWGFM"
    r = requests.get(url)
    return r.json()

# Make tool list


tools = [get_stock_price,fetch_title]

# Make the LLM tool-aware
# llm_with_tools = llm.bind_tools(tools)
# llm_with_tools = create_react_agent(llm, tools)


class ChatState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]

# graph nodes
def chat_node(state: ChatState):
    """LLM node that may answer or request a tool call."""
    messages = state['messages']
    print("Messages so far:", messages[0].content)
    prompt_text="You are a helpful assistant. {user_input} . You can use the following tools: 1. calculator which takes first_num, second_num and operation(add,sub,mul,div) as input and returns the result of the operation. 2. get_stock_price which takes stock symbol as input and returns the latest stock price 3. fetch_title which takes url as argument and return title. Use the tools only if necessary otherwise answer directly."
    prompt=Prompt(prompt_text,parser=parser,input_variables=["user_input"])
    llm=NormalModel(api_key="sk_e9hrwjet_SJrtYF4VYTYd474dsVN5Krd4",prompt=prompt)
    llm_with_tools = create_react_agent(llm, tools)
    
    response = llm_with_tools.invoke({"user_input": messages[0].content})
    # response = llm_with_tools.invoke({"user_input": messages[0].content})
    print("LLM response:", response)
    return {"messages": response}


tool_node = ToolNode(tools)  

# graph structure
graph = StateGraph(ChatState)
graph.add_node("chat_node", chat_node)
graph.add_node("tools", tool_node)


graph.add_edge(START, "chat_node")

# If the LLM asked for a tool, go to ToolNode; else finish
graph.add_conditional_edges("chat_node", tools_condition)

graph.add_edge("tools", "chat_node")    


chatbot = graph.compile()

# chatbot
# Chat requiring tool
out = chatbot.invoke({"messages": "Fetch the title of a webpage given its URL. -> http://127.0.0.1:5000 using fetch_title tool"})
print("output",out['messages'][-1].content)